2022-03-07 12:46:26,847 (44502/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-03-07 12:46:26,936 (44502/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 672, in connect\n    raise e\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 659, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 260, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 306, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: FATAL:  role "divyanshub" does not exist\n\n'
2022-03-07 12:46:33,199 (44648/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-03-07 12:46:54,959 (44648/MainThread) pgcli.pgexecute ERROR - sql: 'createdb testdb', error: SyntaxError('syntax error at or near "createdb"\nLINE 1: createdb testdb\n        ^\n')
2022-03-07 12:46:54,961 (44648/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 472, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 507, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 168, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "createdb"\nLINE 1: createdb testdb\n        ^\n\n'
2022-03-07 15:11:36,035 (140696/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-03-07 15:11:36,118 (140696/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 672, in connect\n    raise e\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 659, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 260, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 306, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: FATAL:  role "divyanshub" does not exist\n\n'
2022-03-07 15:11:41,692 (140794/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-03-07 15:11:51,024 (140794/MainThread) pgcli.pgexecute ERROR - sql: 'SHOW DATABASE', error: UndefinedObject('unrecognized configuration parameter "database"\n')
2022-03-07 15:11:51,026 (140794/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 472, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 507, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 168, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "database"\n\n'
2022-03-07 15:12:07,225 (140794/MainThread) pgcli.pgexecute ERROR - sql: 'SHOW database testdb', error: SyntaxError('syntax error at or near "testdb"\nLINE 1: SHOW database testdb\n                      ^\n')
2022-03-07 15:12:07,226 (140794/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 472, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 507, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 168, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "testdb"\nLINE 1: SHOW database testdb\n                      ^\n\n'
2022-03-07 15:12:18,408 (140794/MainThread) pgcli.pgexecute ERROR - sql: 'SHOW database testdb', error: SyntaxError('syntax error at or near "testdb"\nLINE 1: SHOW database testdb\n                      ^\n')
2022-03-07 15:12:18,409 (140794/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 472, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 507, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 168, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "testdb"\nLINE 1: SHOW database testdb\n                      ^\n\n'
